run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # Essential linters
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    # Formatting
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/nmn3m/pulsar

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: docs/
      linters:
        - all
    - path: migrations/
      linters:
        - all
  max-issues-per-linter: 50
  max-same-issues: 10
